<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{637ad8fb-d548-4a62-8ad9-cf235c97c63c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbVirtualControlBox : FB_VurtualControlBox;
	fbControlbox : FB_Controlbox;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbVirtualControlBox();
fbControlbox();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>