<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_RealControlBox" Id="{2f9db466-d22d-48c5-b22e-fde183a4ecca}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RealControlBox IMPLEMENTS I_ControlBox
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>